theme: jekyll-theme-cayman
show_downloads: true

github:
  zip_url: https://github.com/SimonAndro/github-contributions-ranking-wordpress-plugin/archive/refs/heads/main.zip
  tar_url: https://github.com/SimonAndro/github-contributions-ranking-wordpress-plugin/archive/refs/heads/main.tar.gz
